create table SELCOMMITTEE_ADMISSIONS_CAMPAIGN_DIRECTION_OF_STUDY_LINK (
    ADMISSIONS_CAMPAIGN_ID varchar(36) not null,
    DIRECTION_OF_STUDY_ID varchar(36) not null,
    primary key (ADMISSIONS_CAMPAIGN_ID, DIRECTION_OF_STUDY_ID)
);
